/**
 * Style Dictionary build pipeline.
 * Reads W3C/DTCG design tokens from `tokens/` and emits:
 *   - SCSS variables + maps        -> projects/design-system/src/styles/tokens/
 *   - CSS custom properties        -> projects/design-system/src/styles/tokens/
 *   - Strongly-typed TS artifacts  -> projects/design-system/src/lib/tokens/
 */
import StyleDictionary from 'style-dictionary';

const SCSS_OUT = 'projects/design-system/src/styles/tokens/';
const TS_OUT = 'projects/design-system/src/lib/tokens/';

const scssVarName = (token) => `$ds-${token.path.join('-')}`;
const cssVarName = (token) => `--ds-${token.path.join('-')}`;

const scssValue = (token) => {
  if (Array.isArray(token.$value)) {
    return token.$value.map((v) => (/\s/.test(v) ? `'${v}'` : v)).join(', ');
  }
  return token.$value;
};

/**
 * `scss/tokens-variables` — flat `$ds-*` SCSS variables for every token, grouped by category comment.
 */
StyleDictionary.registerFormat({
  name: 'scss/tokens-variables',
  format: ({ dictionary, options }) => {
    const header = `// -----------------------------------------------------------------------------\n// AUTO-GENERATED by Style Dictionary. Do not edit directly — edit /tokens/*.json\n// -----------------------------------------------------------------------------\n`;
    const lines = dictionary.allTokens
      .filter((t) => (options.filterType ? t.$type === options.filterType : true))
      .map((t) => `${scssVarName(t)}: ${scssValue(t)}${t.$description ? ` !default; // ${t.$description}` : ' !default;'}`);
    return `${header}\n${lines.join('\n')}\n`;
  },
});

/**
 * `scss/tokens-map` — a single SCSS map (e.g. `$ds-spacers`) built from a token group.
 */
StyleDictionary.registerFormat({
  name: 'scss/tokens-map',
  format: ({ dictionary, options }) => {
    const header = `// -----------------------------------------------------------------------------\n// AUTO-GENERATED by Style Dictionary. Do not edit directly — edit /tokens/*.json\n// -----------------------------------------------------------------------------\n`;
    const tokens = dictionary.allTokens.filter((t) => t.path.join('.').startsWith(options.groupPath));
    const entries = tokens.map((t) => {
      const key = t.path[t.path.length - 1];
      return `  ${/^[0-9]/.test(key) ? key : `'${key}'`}: ${scssValue(t)}`;
    });
    return `${header}\n$${options.mapName}: (\n${entries.join(',\n')}\n) !default;\n`;
  },
});

/**
 * `css/tokens-custom-properties` — `:root { --ds-* }` custom properties for runtime theming.
 */
StyleDictionary.registerFormat({
  name: 'css/tokens-custom-properties',
  format: ({ dictionary }) => {
    const header = `/**\n * AUTO-GENERATED by Style Dictionary. Do not edit directly — edit /tokens/*.json\n */\n`;
    const lines = dictionary.allTokens.map((t) => `  ${cssVarName(t)}: ${scssValue(t)};`);
    return `${header}\n:root {\n${lines.join('\n')}\n}\n`;
  },
});

/** Reads a token's dark-mode override, stored as a DTCG vendor extension. */
const darkValue = (token) => token.$extensions?.['com.novan.dark'];

/**
 * `scss/dark-tokens-custom-properties` — `[data-bs-theme='dark'] { --ds-color-* }` overrides,
 * generated from each color token's `$extensions['com.novan.dark']` value.
 */
StyleDictionary.registerFormat({
  name: 'scss/dark-tokens-custom-properties',
  format: ({ dictionary }) => {
    const header = `// -----------------------------------------------------------------------------\n// AUTO-GENERATED by Style Dictionary. Do not edit directly — edit /tokens/*.json\n// Dark-mode overrides for --ds-color-* custom properties, sourced from each\n// color token's \`$extensions['com.novan.dark']\` value.\n// -----------------------------------------------------------------------------\n`;
    const tokens = dictionary.allTokens.filter((t) => t.path[0] === 'color' && darkValue(t) !== undefined);
    const lines = tokens.map((t) => `  ${cssVarName(t)}: ${darkValue(t)};`);
    return `${header}\n[data-bs-theme='dark'] {\n${lines.join('\n')}\n}\n`;
  },
});

/**
 * `typescript/tokens-module` — interfaces, const enums, and typed const objects for use in components.
 */
StyleDictionary.registerFormat({
  name: 'typescript/tokens-module',
  format: ({ dictionary }) => {
    const header = `/**\n * AUTO-GENERATED by Style Dictionary. Do not edit directly — edit /tokens/*.json\n */\n`;

    const colorTokens = dictionary.allTokens.filter((t) => t.path[0] === 'color');
    const spacingTokens = dictionary.allTokens.filter((t) => t.path[0] === 'spacing' && t.path[1] === 'scale');
    const fontFamilyTokens = dictionary.allTokens.filter((t) => t.path[0] === 'font' && t.path[1] === 'family');
    const fontSizeTokens = dictionary.allTokens.filter((t) => t.path[0] === 'font' && t.path[1] === 'size');

    const toCamel = (path) =>
      path
        .map((seg, i) => (i === 0 ? seg : seg.replace(/(^|-)([a-z0-9])/g, (_, __, c) => c.toUpperCase())))
        .join('');

    const colorEntries = colorTokens.map((t) => `  '${t.path.slice(1).join('.')}': '${t.$value}',`);
    const colorKeyUnion = colorTokens.map((t) => `'${t.path.slice(1).join('.')}'`).join(' | ');
    const darkColorEntries = colorTokens.map(
      (t) => `  '${t.path.slice(1).join('.')}': '${darkValue(t) ?? t.$value}',`,
    );

    const spacingEnumEntries = spacingTokens
      .map((t) => `  Space${t.path[t.path.length - 1]} = '${t.$value}',`)
      .join('\n');

    const fontFamilyEntries = fontFamilyTokens
      .map((t) => `  ${toCamel(t.path.slice(2))}: [${t.$value.map((v) => `'${v}'`).join(', ')}] as const,`)
      .join('\n');

    const fontSizeEntries = fontSizeTokens
      .map((t) => `  ${toCamel(t.path.slice(2))}: '${t.$value}',`)
      .join('\n');

    return `${header}
/** Union of every color token path, e.g. \`brand.primary\`, \`neutral.gray-900\`. */
export type DesignTokenColorKey = ${colorKeyUnion};

/** Flat map of color token key -> resolved hex/CSS value. */
export const colorTokens: Record<DesignTokenColorKey, string> = {
${colorEntries.join('\n')}
};

/** Flat map of color token key -> dark-mode hex/CSS value (falls back to the light value when no dark override is defined). */
export const darkColorTokens: Record<DesignTokenColorKey, string> = {
${darkColorEntries.join('\n')}
};

/** Spacing scale (1-16) mirroring the Bootstrap \`$ds-spacers\` SCSS map. */
export const enum SpacingScale {
${spacingEnumEntries}
}

/** Font family stacks generated from typography tokens. */
export const fontFamilyTokens = {
${fontFamilyEntries}
};

/** Named font sizes generated from typography tokens. */
export const fontSizeTokens = {
${fontSizeEntries}
};

export interface DesignTokens {
  colors: typeof colorTokens;
  darkColors: typeof darkColorTokens;
  spacing: typeof SpacingScale;
  fontFamilies: typeof fontFamilyTokens;
  fontSizes: typeof fontSizeTokens;
}
`;
  },
});

export default {
  source: ['tokens/**/*.tokens.json'],
  usesDtcg: true,
  platforms: {
    scss: {
      buildPath: SCSS_OUT,
      files: [
        {
          destination: '_colors.tokens.scss',
          format: 'scss/tokens-variables',
          filter: (t) => t.path[0] === 'color',
        },
        {
          destination: '_typography.tokens.scss',
          format: 'scss/tokens-variables',
          filter: (t) => t.path[0] === 'font',
        },
        {
          destination: '_spacing.tokens.scss',
          format: 'scss/tokens-variables',
          filter: (t) => t.path[0] === 'spacing',
        },
        {
          destination: '_spacers.map.scss',
          format: 'scss/tokens-map',
          options: { groupPath: 'spacing.scale', mapName: 'ds-spacers' },
        },
        {
          destination: '_theme-colors.map.scss',
          format: 'scss/tokens-map',
          options: { groupPath: 'color.brand', mapName: 'ds-theme-colors' },
        },
        {
          destination: '_dark-colors.tokens.scss',
          format: 'scss/dark-tokens-custom-properties',
        },
        {
          destination: '_elevation.tokens.scss',
          format: 'scss/tokens-variables',
          filter: (t) => t.path[0] === 'elevation',
        },
        {
          destination: '_motion.tokens.scss',
          format: 'scss/tokens-variables',
          filter: (t) => t.path[0] === 'motion',
        },
        {
          destination: 'tokens.css',
          format: 'css/tokens-custom-properties',
        },
      ],
    },
    ts: {
      buildPath: TS_OUT,
      files: [
        {
          destination: 'design-tokens.ts',
          format: 'typescript/tokens-module',
        },
      ],
    },
  },
};
