import type { Meta, StoryObj } from '@storybook/angular';
import { DsBrandDarkModeFoundationComponent } from './dark-mode-foundation.component';

const meta: Meta<DsBrandDarkModeFoundationComponent> = {
  title: 'Foundations/Brand/Dark Mode',
  component: DsBrandDarkModeFoundationComponent,
  tags: ['autodocs'],
  parameters: {
    layout: 'padded',
    docs: {
      subtitle: 'The real dark-mode mechanism, live: data-bs-theme, --ds-color-* tokens, and their published dark values',
      description: {
        component:
          'Dark mode is a single `data-bs-theme="dark"` attribute that flips every `--ds-color-*` custom property to its dark value, generated by Style Dictionary from each color token\'s dark override. Toggle the switch to preview real components re-theming live, and browse every color token\'s light/dark pair sourced from the actual published `colorTokens`/`darkColorTokens` API. Independent of this page\'s toggle, every story in this Storybook also has a global "Theme" toolbar item (top toolbar) that previews dark mode for any component.',
      },
    },
  },
};

export default meta;
type Story = StoryObj<DsBrandDarkModeFoundationComponent>;

export const Default: Story = {};
