import { ChangeDetectionStrategy, Component, computed, signal } from '@angular/core';
import { colorTokens, darkColorTokens, type DesignTokenColorKey } from '../../tokens/design-tokens';

interface TokenSwatch {
  readonly key: DesignTokenColorKey;
  readonly light: string;
  readonly dark: string;
  readonly changed: boolean;
}

/**
 * Interactive Storybook doc page proving out the design system's real
 * dark-mode mechanism: setting `data-bs-theme="dark"` on an ancestor element
 * flips every `--ds-color-*` custom property (generated by Style Dictionary
 * from `$extensions['com.novan.dark']` in `/tokens/color.tokens.json`), which
 * every component reads directly. Unlike Foundations/Brand, this page uses
 * the actual published token values (`colorTokens`/`darkColorTokens`) rather
 * than a standalone role-assignment palette.
 */
@Component({
  selector: 'ds-brand-dark-mode-foundation',
  standalone: true,
  templateUrl: './dark-mode-foundation.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    class: 'ds-bfd',
    '[attr.data-bs-theme]': 'darkMode() ? "dark" : null',
  },
})
export class DsBrandDarkModeFoundationComponent {
  readonly darkMode = signal(false);

  toggleDarkMode(): void {
    this.darkMode.update((value) => !value);
  }

  readonly swatches: readonly TokenSwatch[] = (Object.keys(colorTokens) as DesignTokenColorKey[]).map((key) => ({
    key,
    light: colorTokens[key],
    dark: darkColorTokens[key],
    changed: colorTokens[key] !== darkColorTokens[key],
  }));

  readonly changedCount = computed(() => this.swatches.filter((s) => s.changed).length);
}
