/*
 * Public API Surface of @my-org/design-system
 */

// Components
export * from './lib/components/hero/hero.component';
export * from './lib/components/main-nav/main-nav.component';
export * from './lib/components/header/header.component';
export * from './lib/components/footer/footer.component';
export * from './lib/components/sidebar/sidebar.component';
export * from './lib/components/cookie-banner/cookie-banner.component';
export * from './lib/components/breadcrumb/breadcrumb.component';

// Models
export * from './lib/models/nav-item.model';

// Design tokens (generated by Style Dictionary — see /tokens and style-dictionary.config.mjs)
export * from './lib/tokens/design-tokens';
